In [1]:
import numpy as np

In [2]:
#1D data

In [3]:
a=np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
a.shape

(3,)

In [6]:
# wap to create a array of 23,45,78,1.
x=np.array([23,45,78,1])
x

array([23, 45, 78,  1])

In [7]:
x.shape

(4,)

In [8]:
# 2D data-----

x=np.array([[1,2,3],[4,5,6]])

In [9]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
x.shape

(2, 3)

In [11]:
x.size

6

In [12]:
#3D data----

x=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [13]:
x

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [15]:
x.ndim

3

In [16]:
x.shape

(1, 3, 3)

In [17]:
x.size

9

In [ ]:
# slicing & indexing-----

# slicing in 1D data-----

a

In [ ]:
a[0]

In [ ]:
a[4]

In [ ]:
a[2]

In [ ]:
# slicing in 2D data-----

x=np.array([[67,80,43],[30,43,21]])
x

In [ ]:
x[0,1]

In [ ]:
x[0,0]

In [ ]:
x[1,2]

In [ ]:
x[2,1]

In [ ]:
# slicing in 3D data-----

x=np.array([[[10,45,34],[56,79,87],[78,90,21]]])
x

In [ ]:
x[2,2]

In [ ]:
x[2,2,2]

In [ ]:
x[0,2,2]

In [ ]:
x[0,1,0]

In [ ]:
# function to create arrays
# zeros
#ones

z=np.zeros(4)

In [ ]:
z

In [ ]:
z=np.zeros([4,5])

In [ ]:
z

In [ ]:
np.zeros([[4,5,6]])

In [ ]:
# wap to create a empty array

np.zeros([0,3])

In [ ]:
np.zeros([4,5,2])

In [ ]:
#ones------
np.ones(3)

In [ ]:
np.ones([3,4])

In [ ]:
np.ones(0)

In [ ]:
np.ones([0,4])

In [ ]:
np.ones([4,0])

In [ ]:
# axix----0,1

In [ ]:
y=np.array([[2,4,5],[6,7,8]])

In [ ]:
y

In [ ]:
y.sum()

In [ ]:
y.sum(axis=0)

In [ ]:
y.sum(axis=1)

In [ ]:
#arange----

np.arange(4)

In [ ]:
np.arange(1,5)

In [ ]:
np.arange(5,20,6)