In [1]:
import numpy as np

In [2]:
x=np.array([[3,7,9],[6,7,8]])
x

array([[3, 7, 9],
       [6, 7, 8]])

In [3]:
y=np.array([[7,8,4],[2,8,3]])
y

array([[7, 8, 4],
       [2, 8, 3]])

In [6]:
np.concatenate((x,y))

array([[3, 7, 9],
       [6, 7, 8],
       [7, 8, 4],
       [2, 8, 3]])

In [8]:
# concatinate by rows--
np.concatenate((x,y),axis=1)

array([[3, 7, 9, 7, 8, 4],
       [6, 7, 8, 2, 8, 3]])

In [13]:
np.hstack((x,y))

array([[3, 7, 9, 7, 8, 4],
       [6, 7, 8, 2, 8, 3]])

In [16]:
# concatenate by columns----
np.concatenate((x,y),axis=0)

array([[3, 7, 9],
       [6, 7, 8],
       [7, 8, 4],
       [2, 8, 3]])

In [18]:
z=np.vstack((x,y))
z

array([[3, 7, 9],
       [6, 7, 8],
       [7, 8, 4],
       [2, 8, 3]])

In [19]:
# split
np.split(z,2)

[array([[3, 7, 9],
        [6, 7, 8]]),
 array([[7, 8, 4],
        [2, 8, 3]])]

In [28]:
# column wise split---
z

array([[3, 7, 9],
       [6, 7, 8],
       [7, 8, 4],
       [2, 8, 3]])

In [30]:
np.split(z,2,axis=0)

[array([[3, 7, 9],
        [6, 7, 8]]),
 array([[7, 8, 4],
        [2, 8, 3]])]

In [31]:
np.split(z,2,axis=1)

ValueError: array split does not result in an equal division