In [1]:
import numpy as np

In [7]:
# arange---work as loop(start point,end point,steps)

np.arange(5)

array([0, 1, 2, 3, 4])

In [8]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [9]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
#linespace--
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [14]:
np.linspace(5,10,3)

array([ 5. ,  7.5, 10. ])

In [17]:
#reshape
# change 1d arry into 2d arreay

arr_1d=np.array([4,2,6,9])
arr_1d

array([4, 2, 6, 9])

In [18]:
arr_1d.reshape(2,2)

array([[4, 2],
       [6, 9]])

In [20]:
arr_1d=np.array([1,2,3,8,5,6,7,8,9,5,4,8,1,2,3,9])
arr_1d

array([1, 2, 3, 8, 5, 6, 7, 8, 9, 5, 4, 8, 1, 2, 3, 9])

In [23]:
arr_1d.reshape(4,4)

array([[1, 2, 3, 8],
       [5, 6, 7, 8],
       [9, 5, 4, 8],
       [1, 2, 3, 9]])

In [25]:
# change into 3D
arr_1d.reshape(2,2,4)

array([[[1, 2, 3, 8],
        [5, 6, 7, 8]],

       [[9, 5, 4, 8],
        [1, 2, 3, 9]]])

In [27]:
arr_1d.reshape(4,2,2)

array([[[1, 2],
        [3, 8]],

       [[5, 6],
        [7, 8]],

       [[9, 5],
        [4, 8]],

       [[1, 2],
        [3, 9]]])

In [30]:
array_3d=np.arange(1,31).reshape(3,2,5)
array_3d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

In [32]:
#Revel--- multidim ko 1D mai chage
array_3d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [33]:
# flatten
array_3d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [34]:
# Transpose matrix

arr=np.array([[1,2,3,4],[6,7,3,2]])
arr

array([[1, 2, 3, 4],
       [6, 7, 3, 2]])

In [35]:
arr.T

array([[1, 6],
       [2, 7],
       [3, 3],
       [4, 2]])

In [36]:
#ADD
x=np.array([[3,5,3],[7,9,4],[2,5,9]])
x

array([[3, 5, 3],
       [7, 9, 4],
       [2, 5, 9]])

In [37]:
y=np.array([[11,3,5],[9,1,2],[1,1,1]])
y

array([[11,  3,  5],
       [ 9,  1,  2],
       [ 1,  1,  1]])

In [38]:
x+y

array([[14,  8,  8],
       [16, 10,  6],
       [ 3,  6, 10]])

In [39]:
np.add(x,y)

array([[14,  8,  8],
       [16, 10,  6],
       [ 3,  6, 10]])

In [40]:
#max value---
x

array([[3, 5, 3],
       [7, 9, 4],
       [2, 5, 9]])

In [41]:
x.max()

9

In [42]:
x.max(0)
# column wise max value

array([7, 9, 9])

In [43]:
x.max(1)
#row wise max value

array([5, 9, 9])

In [44]:
x.min()

2

In [45]:
x.min(1)

array([3, 4, 2])

In [46]:
x.min(0)

array([2, 5, 3])

In [49]:
#AVG
x.mean()

5.222222222222222

In [50]:
x.mean(0)

array([4.        , 6.33333333, 5.33333333])

In [51]:
x.mean(1)

array([3.66666667, 6.66666667, 5.33333333])

In [52]:
#Sum
x.sum()

47

In [53]:
x.sum(0)

array([12, 19, 16])

In [54]:
x.sum(1)

array([11, 20, 16])

In [57]:
# square root--
np.sqrt(x)

array([[1.73205081, 2.23606798, 1.73205081],
       [2.64575131, 3.        , 2.        ],
       [1.41421356, 2.23606798, 3.        ]])

In [ ]:
# standar