In [1]:
import numpy as np

In [2]:
#1D data

In [3]:
a=np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
a.shape

(3,)

In [6]:
# wap to create a array of 23,45,78,1.
x=np.array([23,45,78,1])
x

array([23, 45, 78,  1])

In [7]:
x.shape

(4,)

In [8]:
# 2D data-----

x=np.array([[1,2,3],[4,5,6]])

In [9]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
x.shape

(2, 3)

In [11]:
x.size

6

In [12]:
#3D data----

x=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [13]:
x

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [14]:
x.ndim

3

In [15]:
x.shape

(1, 3, 3)

In [16]:
x.size

9

In [17]:
# slicing & indexing-----

# slicing in 1D data-----

a

array([1, 2, 3])

In [18]:
a[0]

1

In [19]:
a[4]

IndexError: index 4 is out of bounds for axis 0 with size 3

In [20]:
a[2]

3

In [21]:
# slicing in 2D data-----

x=np.array([[67,80,43],[30,43,21]])
x

array([[67, 80, 43],
       [30, 43, 21]])

In [22]:
x[0,1]

80

In [23]:
x[0,0]

67

In [24]:
x[1,2]

21

In [25]:
x[2,1]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [26]:
# slicing in 3D data-----

x=np.array([[[10,45,34],[56,79,87],[78,90,21]]])
x

array([[[10, 45, 34],
        [56, 79, 87],
        [78, 90, 21]]])

In [27]:
x[2,2]

IndexError: index 2 is out of bounds for axis 0 with size 1

In [28]:
x[2,2,2]

IndexError: index 2 is out of bounds for axis 0 with size 1

In [29]:
x[0,2,2]

21

In [30]:
x[0,1,0]

56

In [31]:
# function to create arrays
# zeros
#ones

z=np.zeros(4)

In [32]:
z

array([0., 0., 0., 0.])

In [33]:
z=np.zeros([4,5])

In [34]:
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
np.zeros([[4,5,6]])

TypeError: 'list' object cannot be interpreted as an integer

In [36]:
# wap to create a empty array

np.zeros([0,3])

array([], shape=(0, 3), dtype=float64)

In [37]:
np.zeros([4,5,2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [38]:
#ones------
np.ones(3)

array([1., 1., 1.])

In [39]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
np.ones(0)

array([], dtype=float64)

In [41]:
np.ones([0,4])

array([], shape=(0, 4), dtype=float64)

In [42]:
np.ones([4,0])

array([], shape=(4, 0), dtype=float64)

In [43]:
# axix----0,1

In [44]:
y=np.array([[2,4,5],[6,7,8]])

In [45]:
y

array([[2, 4, 5],
       [6, 7, 8]])

In [46]:
y.sum()

32

In [47]:
y.sum(axis=0)

array([ 8, 11, 13])

In [48]:
y.sum(axis=1)

array([11, 21])

In [49]:
#arange----

np.arange(4)

array([0, 1, 2, 3])

In [50]:
np.arange(1,5)

array([1, 2, 3, 4])

In [51]:
np.arange(5,20,6)

array([ 5, 11, 17])