In [1]:
import numpy as np

In [2]:
#Sclicing in 1D array
arr=np.array([6,8,3,5])
arr

array([6, 8, 3, 5])

In [3]:
arr[0]

6

In [4]:
arr[3]

5

In [5]:
#Sclincing in 2D array--

arr=np.array([[1,4,7],[4,7,8]])
arr

array([[1, 4, 7],
       [4, 7, 8]])

In [6]:
arr[0]

array([1, 4, 7])

In [7]:
arr[1]

array([4, 7, 8])

In [8]:
arr[0][0]

1

In [9]:
arr[0][2]

7

In [10]:
arr[1][0]

4

In [11]:
arr[1][1]

7

In [14]:
#Sclicing in 3D aaray--
arr=np.array([[[5,7,9],[12,56,78],[45,67,90]]])
arr

array([[[ 5,  7,  9],
        [12, 56, 78],
        [45, 67, 90]]])

In [18]:
arr[0][0]

array([5, 7, 9])

In [19]:
arr[0][1]

array([12, 56, 78])

In [20]:
arr[0][2]

array([45, 67, 90])

In [21]:
arr[0][2][2]

90

In [22]:
arr[0][1][2]

78