In [1]:
import numpy as np

In [2]:
#1D array--
array_1d=np.array([4,3,6])
array_1d

array([4, 3, 6])

In [3]:
type(array_1d)

numpy.ndarray

In [5]:
array_1d.size

3

In [7]:
array_1d.shape

(3,)

In [9]:
#2D array--
array_2d=np.array([[23,43,12],[34,89,3]])
array_2d

array([[23, 43, 12],
       [34, 89,  3]])

In [11]:
array_2d.shape

(2, 3)

In [12]:
array_2d.size

6

In [13]:
#3D array---
array_3d=np.array([[[1,2,4],[5,7,8],[2,9,4]]])
array_3d

array([[[1, 2, 4],
        [5, 7, 8],
        [2, 9, 4]]])

In [14]:
array_3d.size

9

In [15]:
array_3d.shape

(1, 3, 3)

In [16]:
#ones matrix---
np.ones(5)
# it gives column number

array([1., 1., 1., 1., 1.])

In [19]:
np.ones((3,4))
#it gives us row & column number respectally

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.ones((5,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [23]:
np.ones((5,5),dtype=bool)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [24]:
np.ones((3),dtype=int)

array([1, 1, 1])

In [25]:
#zeros matrix
np.zeros(2)

array([0., 0.])

In [26]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.zeros((5,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [30]:
# empty matrix
np.empty((3,3))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.86919378e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 0.00000000e+000]])

In [31]:
np.empty(3)

array([9.12458190e-313, 7.21478569e-313, 6.36598742e-314])