In [2]:
#empty
#linspace
#aggregation function

import numpy as np

In [10]:
np.empty(3)

array([1.05749540e-311, 0.00000000e+000, 1.06112184e-153])

In [11]:
np.empty([2,5])

array([[3.03181047e+180, 2.95842784e+137, 7.33720905e+223,
        6.88786594e+127, 3.69028917e+180],
       [3.38758803e-307, 3.59248754e-289, 1.09385188e-303,
        1.09385187e-303, 1.09402988e-303]])

In [14]:
#linspace------

np.linspace(1,4,3)

array([1. , 2.5, 4. ])

In [17]:
np.linspace(5,100,40)

array([  5.        ,   7.43589744,   9.87179487,  12.30769231,
        14.74358974,  17.17948718,  19.61538462,  22.05128205,
        24.48717949,  26.92307692,  29.35897436,  31.79487179,
        34.23076923,  36.66666667,  39.1025641 ,  41.53846154,
        43.97435897,  46.41025641,  48.84615385,  51.28205128,
        53.71794872,  56.15384615,  58.58974359,  61.02564103,
        63.46153846,  65.8974359 ,  68.33333333,  70.76923077,
        73.20512821,  75.64102564,  78.07692308,  80.51282051,
        82.94871795,  85.38461538,  87.82051282,  90.25641026,
        92.69230769,  95.12820513,  97.56410256, 100.        ])

In [3]:
# aggregation function------->
# sum ,min ,max,avg/mean

x=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [19]:
x

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [20]:
x.sum()

45

In [22]:
x.max()

9

In [23]:
x.min()

1

In [26]:
x.mean()

5.0

In [4]:
x.mean(axis=0)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [29]:
x.mean(axis=1)

array([[4., 5., 6.]])

In [49]:
#median
#odd num---middle value is median
# even num--(n+1)/2

a=[45,9,6,3,2,1]

In [50]:
a

[45, 9, 6, 3, 2, 1]

In [51]:
a.sort()

In [52]:
a

[1, 2, 3, 6, 9, 45]

In [53]:
median=(a[2]+a[3])/2

In [54]:
median

4.5

In [60]:
#sort function-----
x=np.array([[[2,5,3],[56,32,12],[80,40,68]]])
x

array([[[ 2,  5,  3],
        [56, 32, 12],
        [80, 40, 68]]])

In [61]:
#ascending order
x.sort()

In [62]:
x

array([[[ 2,  3,  5],
        [12, 32, 56],
        [40, 68, 80]]])

In [63]:
# argmax
# argmin
#argsort

x=np.array([[[2,5,3],[56,32,12],[80,40,68]]])

In [64]:
x

array([[[ 2,  5,  3],
        [56, 32, 12],
        [80, 40, 68]]])

In [65]:
x.argmax()

6

In [66]:
x.argmin()

0

In [67]:
x.argsort()

array([[[0, 2, 1],
        [2, 1, 0],
        [1, 2, 0]]], dtype=int64)

In [68]:
#searching
x=np.array([100,23,45,68,90,42,11])
x

array([100,  23,  45,  68,  90,  42,  11])

In [69]:
np.where(x%2==0)

(array([0, 3, 4, 5], dtype=int64),)

In [70]:
np.where(x%2!=0)

(array([1, 2, 6], dtype=int64),)

In [71]:
# transpose matrix------

x=np.array([[1,3,5],[56,78,12]])

In [72]:
x

array([[ 1,  3,  5],
       [56, 78, 12]])

In [74]:
x.T

array([[ 1, 56],
       [ 3, 78],
       [ 5, 12]])

In [77]:
# wap to add two different data

x=np.array([[[1,3,4],[7,9,2],[3,8,1]]])
y=np.array([2,5,7])
z=x+y
z

array([[[ 3,  8, 11],
        [ 9, 14,  9],
        [ 5, 13,  8]]])

In [78]:
x=np.array([[[1,3,4],[7,9,2]]])
y=np.array([2,5,7])
z=x+y
z

array([[[ 3,  8, 11],
        [ 9, 14,  9]]])

In [79]:
x=np.array([[[1,3,4],[7,9,2],[3,8]]])
y=np.array([2,5,7])
z=x+y
z

C:\Users\saura\AppData\Local\Temp\ipykernel_25872\3244083779.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x=np.array([[[1,3,4],[7,9,2],[3,8]]])


TypeError: can only concatenate list (not "int") to list

In [ ]:
x =np.array([[1]])